# Generated by Django 3.1.7 on 2021-04-01 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=150, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('post', models.CharField(max_length=150, verbose_name='Должность')),
                ('tel', models.CharField(max_length=150, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Export', 'export'), ('Import', 'import')], max_length=150, verbose_name='Тип записи')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Марка/Модель')),
                ('plate_number', models.CharField(max_length=150, verbose_name='Госномер')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date_appointed', models.DateTimeField(auto_now_add=True, verbose_name='Назначеная дата')),
                ('comment', models.CharField(max_length=150, verbose_name='Коментарий')),
                ('done', models.BooleanField(default=True, verbose_name='Видимость')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.city', verbose_name='Город')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.contractor', verbose_name='Контрагент')),
                ('forwarder', models.ManyToManyField(related_name='forwarder', to='log.Employer', verbose_name='Экспедитор')),
                ('responsible', models.ManyToManyField(related_name='responsible', to='log.Employer', verbose_name='Ответственный')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.type', verbose_name='Тип')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
