# Generated by Django 3.0.7 on 2021-04-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='comment',
            field=models.CharField(default=0, max_length=150, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='date_appointed',
            field=models.DateTimeField(verbose_name='Назначеная дата'),
        ),
        migrations.AlterField(
            model_name='record',
            name='done',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Export', 'export'), ('Import', 'import'), ('Touch', 'touch')], max_length=150, verbose_name='Тип записи'),
        ),
    ]
