# Generated by Django 3.0.7 on 2021-04-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20210417_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_appointed',
            field=models.DateField(verbose_name='Назначеная дата'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
