# Generated by Django 3.0.7 on 2021-04-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20210417_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('tel', models.CharField(max_length=150, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Экспедитор',
                'verbose_name_plural': 'Экспедиторы',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('tel', models.CharField(max_length=150, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Коментарий'),
        ),
        migrations.RemoveField(
            model_name='record',
            name='forwarder',
        ),
        migrations.RemoveField(
            model_name='record',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.AddField(
            model_name='record',
            name='forwarder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.Forwarder', verbose_name='Экспедитор'),
        ),
        migrations.AddField(
            model_name='record',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.Manager', verbose_name='Ответственный'),
        ),
    ]
